apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-nl-tls
spec:
  secretName: multi-k8s-nl-tls
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.nl
  dnsNames:
    - multi-k8s.nl
    - www.multi-k8s.nl
  acme:
    config:
      - http01:
          ingressClass:nginx
        domains:
          - multi-k8s.nl
          - www.multi-k8s.nl
      