apiVersion: certmanager.k8s.io/v1aplha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'patrick.peek@pacurro.nl'
    privateKeySecretRef:
      name: letsencrypt-prod
      solvers:
      - http01:
          ingress:
            class: nginx
